### ISSUE TITLE
Fix sortable behaviour

### ISSUE THREAD

**Issue by robinpoort** [joomlatools/joomlatools-platform#287]
sortable modules doesn't seem to be working properly: 
http://joomla.box/joomlatools-platform/administrator/index.php?option=com_modules&view=modules

You have to click on the table header first but that doesn't seem to be possible when `Footable` or `floatThead` is enabled. You can disable these JS libraries temporary by removing the `table--fixed` and `footable` classes from the table and reload the page.

**Comment by johanjanssens** [comment]
@robinpoort I suspect that the fixes here are javascript related ?

**Comment by robinpoort** [comment]
@johanjanssens Probably yeah.

Also: Nooku framework still does sorting the Joomla 1.5 way (by using arrows). Joomla is now using drag and drop rows. It'd be best to have the same user experience over the two different types of pages. 

But since this is all JS related and buried deep into the code (as far as I can see) there's nothing much I can do here.

**Comment by johanjanssens** [comment]
@allanpilarca Can you check if this issue still exists in platform and if so try to fix it?

**Comment by allanpilarca** [comment]
@johanjanssens 

I temporarily removed `table--fixed` and `footable` as @robinpoort suggested in the ticket description then im able to sort the modules, This is working only when `joomlatools-platform-content` is installed. Trying it with plain `joomlatools-platform` without any extensions returns this error `Fatal error: Class 'ContentTableUcmType' not found in /var/www/jt-test/lib/libraries/cms/model/admin.php on line 1310`.

The class `ContentTableUcmType` is used in `saveOrder` method and some other methods in `JModelAdmin` but its only included in `joomlatools-platform-content`.

**Comment by johanjanssens** [comment]
@allanpilarca Will have a look at this how to solve it best.

**Comment by allanpilarca** [comment]
Note: The issue regarding the table header title for sorting being unclickable is cause by tooltip and floatThead conflict. Updating the Joomlatools UI in the template may fix this since floatThead is no longer included in the latest Joomlatools UI.

**Comment by johanjanssens** [comment]
@robinpoort Should we close this issue too, or leave it open for new template, or create a note in the template issue about this?

**Comment by robinpoort** [comment]
@johanjanssens We can close this. I've already worked on drag-drop a bit in new platform. We can open a new ticket when it comes up in the new template as a problem :)

**Comment by johanjanssens** [comment]
Oki done.

**Comment by allanpilarca** [comment]
Just an FYI even the sorting is fix in the template the sorting will still not work in the platform unless the `joomlatools-platform-content` is installed because sorting and other methods in `JModelAdmin` are using the `ContentTableUcmType` class which is only included in the `joomlatools-platform-content`.

**Comment by johanjanssens** [comment]
Thanks @allanpilarca  I have that one on my personal todo.

**Comment by allanpilarca** [comment]
Trying to check this, @robinpoort seems the sortable handler is removed in the modules view?

@johanjanssens is it a good idea if we move the `ContentTableUcmType` and some other classes that are needed for sorting in the platform instead in `platform-content` ?

All sorting in the platform are not working aside from menu sorting because it handles its own sorting. Other sorting uses `JModelAdmin` that uses `ContentTableUcmType` when saving the ordering.

**Comment by allanpilarca** [comment]
@johanjanssens another solution i made is to check if `com_content` is enabled, the run the code if its installed. The code that requires `ContentTableUcmType` is used to manage the tags when saving the ordering. Since if com:content is not installed by default in the platfom its no need to apply it.

**Comment by robinpoort** [comment]
@allanpilarca Yeah seems the sorting for modules got lost. Want me to put them back into place?

**Comment by allanpilarca** [comment]
@robinpoort yes please, it's needed to allow the user to sort the modules. Thanks!

**Comment by robinpoort** [comment]
@allanpilarca Fixed in branch feature/287

**Comment by allanpilarca** [comment]
@robinpoort thanks! :)

**Comment by johanjanssens** [comment]
@allanpilarca Does this require more review, or can it be closed?
