### ISSUE TITLE
Upgrade to Joomla 3.6.5

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-platform#315]

**Comment by allanpilarca** [comment]
Applied and tested in staging site.

@stevenrombauts i encountered ERR_CONTENT_DECODING_FAILED error when trying to view the [create new article page](https://staging.scicasts.com/administrator/index.php?option=com_content&task=article.add), this happens because the gzip page compression is enable in the joomla configuration. Seems we need to enable gzip compression in the nginx. I temporarily disabled this in the staging site.

**Comment by allanpilarca** [comment]
@johanjanssens @stevenrombauts 

Just an update for this ticket
Working Extensions:
- joomlatools-platform-content
- joomlatools-platform-categories
- joomlatools-platform-tags
- joomlatools-platform-media
- com_jxtreadinglinglist (Reading List)
- com_jce
- com_jsn (Easy Profile)
- com_plotalot
- com_widgetkit
- plg_imgresizecache

Removed Core Extensions:
- com_banners
- com_newsfeeds
- com_postinstall
- com_joomlaupdate
- com_search
- com_mailto
- com_ajax
- com_wrapper

Todo:
- com_komento
- com_fieldsattach
- com_dbreplacer
- com_advancedmodules
- com_advancedtemplates
- com_contenttemplater
- Update com_logman and joomlatools-framework to latest. The current version installed is 2.1.2
- Remove com_extman

Since we are planning to replace the com_acymailing and com_finder i skip fixing these extensions.

The com_fieldsattach is currently use to add a menu item id in article edit page and use that in template to get the params of the menu they set. Since they are just using it for a single field we can just replace it and just use a plugin.

Questions:
- The com_komento extensions is currently use for commenting in articles under Insights category, there is also a link in the dashboard that display user's profile that list the comments/likes he made but i havent seen any data in the database that someone made a comment, just a sample comment exists in the database. Are we still keeping this extension? If yes then i will continue fixing this to make it work in the platform.
- Seems we can remove the com_dbreplacer? since we have full acess to database and we can apply any changes to it.
- Do i still need to update joomlatools-platform-media to joomla 3.6.5? then apply it here?

**Comment by allanpilarca** [comment]
@johanjanssens @stevenrombauts 

For testing you can run this command:

```
curl -s https://gist.githubusercontent.com/allanpilarca/431337ac5b9f479fb6f741c40ed37376/raw/3b8f891529862557a34fef9c9209d214dd8b171d/test-joomlatools-platform-1.1.sh | bash
```

This will clone the joomlatools-platform feature/315-joomla-3.6.5-upgrade branch and will install com_content, com_media, com_finder, com_categories and the legacy library.

You can access this in http://joomla.box/joomlatools-platform-1.1-test/web/administrator

**Comment by johanjanssens** [comment]
@allanpilarca If you make changes that could be contributed upstream please log them here: https://github.com/joomlatools/joomlatools-platform/wiki/Upstream-changes 

If you are unsure add the log to the issue description and I will review it and update the wiki. Its important that we properly document the changes we are making.

**Comment by allanpilarca** [comment]
@johanjanssens noted.

Will check the changes and update the wiki and the description of this ticket.

**Comment by allanpilarca** [comment]
hi @johanjanssens,

I added the upstream changes made in this ticket description. I havent added it yet in the wiki.
Because of the changes from joomla 3.6.5 most of the changes in the wiki are outdated, specially the line numbers of the changes. Do we also need to update those?

**Comment by johanjanssens** [comment]
@allanpilarca Thanks. That's fine. We are not going to worry too much about the upstream changes anymore. We don't have the intend to contribute them upstream anymore.

**Comment by johanjanssens** [comment]
@stevenrombauts Shall we merge the PR's to master and then continue testing from there? Specific issues that are found can be fixed in separate issues?
