### ISSUE TITLE
Fix the session creation in enqueueMessage()

### ISSUE THREAD

**Issue by allanpilarca** [joomlatools/joomlatools-platform#317]
The `session_autostart` is set to false by default in frontend that makes the session is not created for guest user. Since the session is not created there are no messages added using `JApplicationCms::enqueueMessage()`. Check if we can fix the session creation when we need it.

see https://github.com/timble/www.scicasts.com/issues/86

**Comment by stevenrombauts** [comment]
@johanjanssens I added code to start an inactive session when `JSession::set()` is called, so that anything that is being stored in a session is still there on the next page: [code](https://github.com/joomlatools/joomlatools-platform/commit/66284bcce6eba1c6c034fe3856a366cfe61407eb#diff-c5b7b169a2934c3b49f87535e26be3d4)

However, calling `$session->start()` alone does not create the session row in the `user_sessions` table. In the application class this is done after auto-starting the session by calling  `JApplicationCms::checkSession()`. This method checks if the session row already exists, and if not create it. 

To solve this I am calling this `checkSession()` method when the session is being saved and closed in `JSessionStorageDatabase::write()`, before it attempts to store the session data: [code](https://github.com/joomlatools/joomlatools-platform/commit/66284bcce6eba1c6c034fe3856a366cfe61407eb#diff-7a285aa00736d0d19a9b3dad86480b1f)

My question here is can this work, or should we consider refactoring this further? For example, we could consider moving the responsibility of _creating_ the session row to the database storage handler as well.

Thoughts?

**Comment by johanjanssens** [comment]
@stevenrombauts Can you create a PR for this? Easier to review the code. Thanks!

**Comment by johanjanssens** [comment]
@stevenrombauts Did you commit the changes as suggested to the branch? I'm happy to review or finish them so we can get 2.0 out of the door.

**Comment by stevenrombauts** [comment]
@johanjanssens I reverted the original changes and applied the less complicated solution. However this does not yet solve the issue in the SciCasts repo. It works perfect on a clean install from current master.

Created PR #324 with this change.

**Comment by johanjanssens** [comment]
@stevenrombauts If this works for platform lets roll it out here and do further testing on Scicasts why it's not working there?

**Comment by stevenrombauts** [comment]
@johanjanssens Check, agreed.
