### ISSUE TITLE
Batch process failed

### ISSUE THREAD

**Issue by allanpilarca** [joomlatools/joomlatools-platform#348]
Batch process failed in menu manager

`Warning Batch process failed with following error: Insufficient information to perform the batch operation.`

**Comment by allanpilarca** [comment]
Note:

This is working fine in backend default template (isis), this error occurs because the fields inside the modal box is not submitted. In default templat the fields inside the modal box should be inside the <form> for it to be included once submitted, this doesnt happen in the template override in elysio. The modal is outside the <form>.

**Comment by robinpoort** [comment]
@allanpilarca I moved the batch modal inside the `<form>` but it doesn't fix the problem. I even renamed the entire `elysio/html/com_menus/items` to `elysio/html/com_menus/items2` as a test with not using any override at all. Still doesn't fix it, it seems there's something inside the elysio template missing that isis does have. Any ideas what might be causing that?

**Comment by allanpilarca** [comment]
@robinpoort seems this line https://github.com/joomlatools/joomlatools-platform/blob/master/web/administrator/templates/elysio/index.php#L159-L167 is moving all modal into `<div id="modal-holder">`, where the `modal-holder` is outside the `<form>` element.

Even we remove the template for `elysio/html/com_menus/items` the modal is still appended to `modal-holder` since its in the `index.php`.

**Comment by robinpoort** [comment]
@allanpilarca Good find! I totally forgot about that thing. I added that because all the Joomla/Bootstrap modals were not showing because of z-index issues.

I went ahead and fixed the z-index issues in kodekit: https://github.com/timble/kodekit-ui/releases/tag/v1.0.1

I've updated to kodekit 1.0.1 in package.json and move all the modals inside the `<form>`s and outside `<div class="k-dynamic-content-holder">` which were also hiding the modals after I removed the JS from `index.php`

I've tested most batch buttons and all seems to be working just fine again. Can you verify?

Pushed in #348-batch

**Comment by allanpilarca** [comment]
@robinpoort tested your fix and its working now as expected. Good work sir :)

Small issue i found in module batch http://joomlatools-platform.test/administrator/index.php?option=com_modules minor styling is needed.

![screen shot 2018-04-02 at 11 28 34 am](https://user-images.githubusercontent.com/194313/38182333-38703fc8-366b-11e8-9832-6f096a31a506.jpg)

Other than that its all working. :)

**Comment by robinpoort** [comment]
@allanpilarca Good find! Should be fixed in feature/348 now

**Comment by allanpilarca** [comment]
@robinpoort that was quick, i can confirmed that this is already working! :)

**Comment by johanjanssens** [comment]
@allanpilarca Can this one be closed?
